language: go

go:
  - 1.6
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  # Decrypts a script that installs an authenticated cookie
  # for git to use when cloning from googlesource.com.
  # Bypasses "bandwidth limit exceeded" errors.
  # See github.com/golang/go/issues/12933
  - openssl aes-256-cbc -K $encrypted_f6c7710202d6_key -iv $encrypted_f6c7710202d6_iv -in dist/gitcookie.sh.enc -out dist/gitcookie.sh -d

install:
  - bash dist/gitcookie.sh
  - go get -t
  - go get golang.org/x/net/http2

os:
 - linux

script:
  - go vet
  - go test -v
  - $HOME/gopath/bin/goveralls -service=travis-ci 